# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 123
  pool: 5

development:
  <<: *default
  database: todo_list

production:
  <<: *default
  database: todo_list
